// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"context"
	"fmt"
)

// ResolverFields list all type and field names that are marked as resolvers. This
// is usefull to automate hooking up lambda functions to them in AppSync.
var ResolverFields = []string{
	"Query.version",
}

// AppSyncResolve uses the input of a direct appsync resolver and calls the correct method the implementation.
// The return value can be used directly as the result data to be returned to AppSync.
func AppSyncResolve(ctx context.Context, rr ResolverRoot, typeName, fieldName string, args map[string]any, parent []byte) (any, error) {

	switch {
	case typeName == "Query" && fieldName == "version":
		return rr.Query().Version(ctx)

	default:
		return nil, fmt.Errorf("no resolver for %s.%s", typeName, fieldName)
	}
}
