// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type Node interface {
	IsNode()
	GetID() int
}

type ProfileOrSink interface {
	IsProfileOrSink()
}

type Bar struct {
	Nr *float64 `json:"nr"`
}

type Profile struct {
	ID          int     `json:"id"`
	Email       *string `json:"email"`
	PhoneNumber *string `json:"phone_number"`
	OtherNode   Node    `json:"other_node"`
}

func (Profile) IsNode()         {}
func (this Profile) GetID() int { return this.ID }

func (Profile) IsProfileOrSink() {}

type Sink struct {
	Name  *string `json:"name"`
	Other *Sink   `json:"other"`
}

func (Sink) IsProfileOrSink() {}
